<div class="jumbotron">
    <h1><?php echo sprintf($this->translate("Welcome to %sMomchil Milev's open source Battleship game.%s"), '<span class="zf-green">', '</span>') ?></h1>

    <p><?php echo $this->translate('Based on Zend Framework 2 with Doctrine 2 Milev Battleship game is an implementation of the very popular board game.
    The idea behind this particular implementation is to provide the users with the ability to play the game against the computer with the ability to cheat.
    In the first version the users play as Guests and can start a new game or play the last one open in their session.') ?></p>

    <p>
        <a class="btn btn-success btn-lg"
           href="<?php echo $this->url('battleship/default', array('controller' => 'index', 'action' => 'newGame')); ?>">
            <?php echo $this->translate('Start a new Battleship Game') ?> &raquo;</a>
        <a class="btn btn-success btn-lg"
           href="<?php echo $this->url('battleship/default', array('controller' => 'index', 'action' => 'play')); ?>">
            <?php echo $this->translate('Play the last started Session Game') ?> &raquo;</a>
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Version 1') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('First version of the game consists of: '); ?>
                <ul>
                    <li><?php echo $this->translate('Creation of game battlefield of 10x10 plates.'); ?></li>
                    <li><?php echo $this->translate('Selecting and random positioning of 3 vessels - 1 Battleship of 5 squares and 2 Destroyers of 4 squares.'); ?></li>
                    <li><?php echo $this->translate('Implementing a web and console versions of the game that share basic game logic behind the scene.'); ?></li>
                    <li><?php echo $this->translate('Providing a simple click way for firing a shot for web version.'); ?></li>
                    <li><?php echo $this->translate('Providing a simple input method for selecting coordinates for the shot for the web version.'); ?></li>
                    <li><?php echo $this->translate('Providing a simple parameters based way of firing shots for the console application.'); ?></li>
                    <li><?php echo $this->translate("Implementing a backdoor cheat path by which the user can spot the computer's vessels."); ?></li>
                    <li>
                        <?php echo $this->translate('Preparing the field for v2 features.'); ?>
                        <ul>
                            <li><?php echo $this->translate('Setting up the database in order to accept v2 feature of user login, user statistics, game statistics, administration of the game configuration.'); ?></li>
                            <li><?php echo $this->translate('Setting up the code in a way that will provide easy way of adding user functionality.'); ?></li>
                        </ul>
                    </li>
                    <li>
                        <?php echo $this->translate('Creating of Install script that setups the initial minimal needed configuration:'); ?>
                        <ul>
                            <li><?php echo $this->translate('Creates the database;'); ?></li>
                            <li><?php echo $this->translate('Inserts records for field size, shot sings.'); ?></li>
                            <li><?php echo $this->translate('Inserts records for vessel types.'); ?></li>
                            <li><?php echo $this->translate('Installs needed vendor code.'); ?></li>
                        </ul>
                    </li>
                    <li><?php echo $this->translate('AJAX-ify the web and mobile apps. (TBD)'); ?></li>
                </ul>
                </p>
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Version 2') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('In the second version of the game we plan to include: '); ?>
                <ul>
                    <li><?php echo $this->translate('User login.'); ?></li>
                    <li><?php echo $this->translate('User games statistics.'); ?></li>
                    <li><?php echo $this->translate('Game statistics.'); ?></li>
                    <li><?php echo $this->translate('Administration of the game configuration like battle field size, vessels types, vessels sizes, vessels count.'); ?></li>
                </ul>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Version 3') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('The third version will present the following addition: '); ?>
                <ul>
                    <li><?php echo $this->translate('Unit testing.'); ?></li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</div>
