<div class="row">
    <div class="col-lg-12">
        <h1>
            <?php echo sprintf(
                $this->translate('Game #%d played by %s #%d'),
                $game->getGameEntity()->getId(),
                $game->getGameEntity()->getPlayer()->getFirstName() . ' ' . $game->getGameEntity()->getPlayer()->getLastName(),
                $game->getGameEntity()->getPlayer()->getId()
            ); ?>
        </h1>
    </div>
</div>

<?php $gameConfig = $game->getGameConfig(); ?>
<div class="row">
    <div class="col-lg-12">
        <?php echo $this->partial('partials/messages'); ?>
    </div>
</div>
<div class="row">
    <?php echo $this->partial('battleship/partials/fire_shot'); ?>
    <?php echo $this->partial('battleship/partials/game_field', array(
        'gameGrid' => $gameGrid,
        'gameConfig' => $gameConfig,
        'cheat' => $cheat,
    )); ?>
    <?php echo $this->partial('battleship/partials/game_info'); ?>
</div>