<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Milev Battleship Game'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles   -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    <!-- CSS SCRIPTS -->
    <?php
    echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ))
//    ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
    ->prependStylesheet($this->basePath() . '/css/style.css')
    ?>

    <!-- JS SCRIPTS -->
    <?php $this->headScript()->appendFile($this->basePath() . '/js/battleship.js') ?>
</head>
<body>
    <a id="skippy" class="sr-only sr-only-focusable" href="#content"><div class="container">
            <span class="skiplink-text"><?php echo $this->translate('Skip to main content'); ?></span>
        </div></a>
    <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
        <div class="container">
            <div class="bs-example" data-example-id="default-navbar">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only"><?php echo $this->translate('Toggle navigation'); ?></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand hidden-lg" href="javascript:;">
                                <?php echo $this->translate('Milev Battleship') ?>
                            </a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li>
                                    <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('battleship') ?>"><?php echo $this->translate('Battleship Results') ?></a>
                                </li>
                                <li class="dropdown">
                                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                        <?php echo $this->translate('Play Battleship') ?>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="<?php echo $this->url('battleship/default', array('controller' => 'index', 'action' => 'play')); ?>"><?php echo $this->translate('Play'); ?></a></li>
                                        <li><a href="<?php echo $this->url('battleship/default', array('controller' => 'index', 'action' => 'play', 'cheat' => 1)); ?>"><?php echo $this->translate('Cheat'); ?></a></li>
                                        <li><a href="<?php echo $this->url('battleship/default', array('controller' => 'index', 'action' => 'newGame')); ?>"><?php echo $this->translate('New Game'); ?></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>
            </div>
        </div>
    </header>

    <div class="container">
        <?php echo $this->partial('partials/messages'); ?>
        <?php echo $this->content; ?>
        <hr />
    </div>
    <!-- /container -->
    <?php echo $this->inlineScript() ?>
</body>
</html>