<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    <!-- CSS SCRIPTS -->
    <?php
    echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ))

        ->prependStylesheet($this->basePath() . '/css/bootstrap-3.0.0/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/zf-table/zf-table.css')
    ?>

    <!-- JS SCRIPTS -->
    <?php
    echo $this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js')
        ->appendFile($this->basePath() . '/js/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/zf-table.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap_3.js')
    ?>

    <style>
        .flash-messages {
            height: 50px;
        }
        .flash-messages .alert ul {
            height: 30px;
            overflow: auto;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>
                &nbsp;<?php echo $this->translate('Skeleton Application') ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('battleship') ?>"><?php echo $this->translate('Battleship Results') ?></a>
                </li>
                <li class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <?php echo $this->translate('Play Battleship') ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->url('battleship/default', array('controller' => 'index', 'action' => 'play')); ?>"><?php echo $this->translate('Play'); ?></a></li>
                        <li><a href="<?php echo $this->url('battleship/default', array('controller' => 'index', 'action' => 'newGame')); ?>"><?php echo $this->translate('New Game'); ?></a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="flash-messages col-lg-12">
            <?php
            // In any of your .phtml files:
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                     &times;
                 </button>
                 <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');

            echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
            echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
            echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
            ?>
        </div>
    </div>
    <?php echo $this->content; ?>
    <hr>
    <footer></footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.dropdown-toggle').dropdown();
    });
</script>
</body>
</html>